sudo: required
dist: trusty
language: node_js
node_js:
    - "8"
before_install:
    - sudo dpkg --add-architecture i386
    - wget -nc https://dl.winehq.org/wine-builds/Release.key
    - sudo apt-key add Release.key
    - sudo apt-add-repository https://dl.winehq.org/wine-builds/ubuntu/
    - sudo apt-get update
    - sudo apt-get install --install-recommends winehq-stable
install:
    - "npm install -g create-react-app"
    - "npm install"
    - "npm install react-scripts"
script:
    - npm run release
branches:
    only:
        - dev
        - release/minor
        - release/major
        - develop/build-script
notifications:
    email:
        thnpt926+travis@gmail.com
