sudo: required
dist: trusty
language: node_js
node_js:
    - "8"
before_install:
    - sudo dpkg --add-architecture i386
    - wget -nc https://dl.winehq.org/wine-builds/Release.key
    - sudo apt-key add Release.key
    - sudo apt-add-repository https://dl.winehq.org/wine-builds/ubuntu/
    - sudo apt update
    - sudo apt install --install-recommends -y winehq-stable
install:
    - "npm install"
before_deploy:
    - "npm run release"
deploy:
  provider: releases
  api_key: P14z8zIfPqtYIBI0kZVyGN38WF9Zv/Osw8a2YdsmVyQCbVRZ+j6nbxoGTepc8PfjFzh6cu2mMQHnJNPMhx5nxqmvnOBL9PWPuYw+q/ncvgLGrWUCgMY+C3OiDUjHVegUk0n2meOjNlYAvAo7vrdpt5TExnhScxsl3BO7dDWwYba4ixng/EXgLZr0QeHfnaZpuCESm6SRNHA1ocYSdTIx+d9GJ9TY/ZcgQm0fts6oUfkDG707qcOWnfJFKzwuD0yxsNMEmy2JKbxS9cd3odby3tiI3jJpQgbQOD0cpayBDozrvphisDdssIjhLyc/ba3AJ9sUpUtyC+zPpfgJ7I+INJUuBp2o5b3Gczezz0l3Pt49xvfIUKUnDLz70wBjF0O7TDXADzt4ytrcBQ+nj5lKjwSchYcE0Ic3LspZJs0EcBCYFr8zpT0htD0Mkdx5J6Gb4pZCffwEPXy3ZpGEtYAGqR8qNl3bOU74r/mQVBLustuQICBU7rzKLwqpXuYSoNsHCHDh3ZaEY4ZwxIYZRGv5CLTWbLHGslE9zfrirb4gwkfjCh+ByOfRVoSILOuXbwMgXoGjMyT7Y2RuvuhlMz0cXZ6z2IBXu/kX8Q9IMp+qPYkghAKjEGSrVX7zmGYyY8wknXZ4UYlF1cnbuqHWl8jETn8Zk6MRi1NbrKNcdG3BkXw=
  file:
    - release/Tsuru-linux-x64.tar.gz
    - release/Tsuru-win32-x64.zip
    - release/Tsuru-mas-x64.zip
    - release/Tsuru-darwin-x64.zip
  skip_cleanup: true
notifications:
    email:
        thnpt926+travis@gmail.com
